import { VoiceModel, StylePreset, DialogueTurn } from './types';

export const GEMINI_VOICES: VoiceModel[] = [
  {
    id: 'Kore',
    name: 'Kore',
    gender: 'Feminine',
    tone: 'Warm & Natural',
    description: 'Clear, articulate, and approachable voice. Exceptional for audiobooks, Sinhala (සිංහල) narration, and friendly guides.',
    badge: 'Popular',
    previewText: 'Say cheerfully with warm articulation: Hello! welcome to AI VOICE STUDIO BY V. Let me guide you through our expressive vocal studio.',
    colorClass: 'bg-[#111] text-[#9966ff] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Puck',
    name: 'Puck',
    gender: 'Masculine',
    tone: 'Upbeat & Energetic',
    description: 'Dynamic, conversational, and enthusiastic tone. Perfect for podcast intros, YouTube voiceovers, Sinhala tech reviews, and marketing.',
    badge: 'Upbeat',
    previewText: 'Speak with lively excitement and high energy: Hey everyone! Welcome back to today’s episode where we dive into next-generation AI voices!',
    colorClass: 'bg-[#111] text-[#ff6699] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Charon',
    name: 'Charon',
    gender: 'Masculine',
    tone: 'Deep & Authoritative',
    description: 'Resonant, calm, and commanding voice. Superior for dramatic trailers, luxury branding, deep Sinhala storytelling, and documentaries.',
    badge: 'Commanding',
    previewText: 'In a deep, resonant, mysterious cinematic tone: In a world driven by innovation, one voice has the power to change everything.',
    colorClass: 'bg-[#111] text-[#a882ff] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Fenrir',
    name: 'Fenrir',
    gender: 'Masculine',
    tone: 'Bold & Expressive',
    description: 'Strong, intense, and emotionally versatile timbre. Outstanding for character acting, Sinhala audio dramas, and high-impact narration.',
    badge: 'Dramatic',
    previewText: 'With bold, passionate intensity: Stand your ground! We have come too far to turn back now. Let our voices be heard!',
    colorClass: 'bg-[#111] text-[#ff80b3] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Zephyr',
    name: 'Zephyr',
    gender: 'Feminine',
    tone: 'Soft & Soothing',
    description: 'Gentle, relaxed, and breathy cadence. Ideal for meditation guides, wellness apps, comforting nighttime stories, and peaceful Sinhala poetry.',
    badge: 'Calming',
    previewText: 'In a soft, gentle, soothing whisper: Take a deep breath in... hold it gently... and exhale all the tension from your day.',
    colorClass: 'bg-[#111] text-[#80b3ff] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Aoede',
    name: 'Aoede',
    gender: 'Feminine',
    tone: 'Elegant & Poetic',
    description: 'Refined, melodic, and highly expressive vocal delivery. Exceptional for speaking Sinhala (සිංහල), classical literature, and luxury presentations.',
    badge: 'Multilingual / Sinhala',
    previewText: 'Speak in authentic native Sri Lankan Sinhala (ශ්‍රී ලාංකික සිංහල) with pure Sinhalese pronunciation without any Tamil or foreign accent: ආයුබෝවන්! AI VOICE STUDIO BY V හරහා ඉතා පැහැදිලි සහ ස්වාභාවික සිංහල හඬවල් නිර්මාණය කළ හැක.',
    colorClass: 'bg-[#111] text-[#00e6cc] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Clio',
    name: 'Clio',
    gender: 'Feminine',
    tone: 'Bright & Articulate',
    description: 'Crisp, engaging, and professional cadence. Outstanding for Sinhala (සිංහල) educational content, tutorials, and corporate announcements.',
    badge: 'Multilingual / Sinhala',
    previewText: 'Speak with bright professional clarity in native Sri Lankan Sinhala (සිංහල) without any Tamil or Indian accent: අද දින පාඩමෙන් අප කෘත්‍රිම බුද්ධිය භාවිතයෙන් ශබ්ද සහ හඬ නිර්මාණය කරන ආකාරය ඉගෙන ගනිමු.',
    colorClass: 'bg-[#111] text-[#ffcc00] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Leda',
    name: 'Leda',
    gender: 'Feminine',
    tone: 'Calm & Versatile',
    description: 'Smooth, balanced, and highly adaptable timbre. Excellent for both English and Sinhala (සිංහල) conversational dialogues and voice assistants.',
    badge: 'Multilingual / Sinhala',
    previewText: 'In a calm, welcoming tone in authentic native Sri Lankan Sinhala without Tamil accent: සුබ දවසක්! ඔබට අවශ්‍ය ඕනෑම භාෂාවකින් සහ ශෛලියකින් හඬ නිර්මාණය කිරීමට අප සූදානම්.',
    colorClass: 'bg-[#111] text-[#70db70] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Orpheus',
    name: 'Orpheus',
    gender: 'Masculine',
    tone: 'Warm & Resonant',
    description: 'Rich baritone voice with heartfelt warmth. Ideal for narrating Sinhala (සිංහල) folk tales, historical documentaries, and inspiring podcasts.',
    badge: 'Multilingual / Sinhala',
    previewText: 'In a warm storytelling voice in authentic Sri Lankan Sinhala (සිංහල) without Tamil accent: එදා රජ කාලයේ ඉඳන්ම අපේ රටේ විවිධ කතාන්දර සහ ජනප්‍රවාද රැසක් පැවත ආවා.',
    colorClass: 'bg-[#111] text-[#ff9933] border-[#222] font-mono shadow-sm',
  },
  {
    id: 'Pegasus',
    name: 'Pegasus',
    gender: 'Masculine',
    tone: 'Confident & Dynamic',
    description: 'Powerful, engaging, and persuasive vocal timbre. Perfect for high-energy commercials, sports commentary, and bold Sinhala promotions.',
    badge: 'Multilingual / Sinhala',
    previewText: 'With bold confident energy in native Sri Lankan Sinhala (සිංහල) without any foreign accent: නවතම තාක්ෂණය සමඟින් ඔබගේ ව්‍යාපාරයත් අලුත් මානයකට ගෙන යන්න! අදම එක්වන්න.',
    colorClass: 'bg-[#111] text-[#3399ff] border-[#222] font-mono shadow-sm',
  },
];

export const STYLE_PRESETS: StylePreset[] = [
  {
    id: 'cheerful',
    label: 'Cheerful & Warm',
    description: 'Bright, friendly, and smiling delivery',
    examplePrefix: 'Say cheerfully with a warm smile: ',
  },
  {
    id: 'sinhala-warm',
    label: 'Sinhala Warm (සිංහල)',
    description: 'Authentic native Sri Lankan Sinhala speech without any Tamil accent',
    examplePrefix: 'Speak in authentic native Sri Lankan Sinhala (ශ්‍රී ලාංකික සිංහල) with warm articulation and pure Sinhalese pronunciation (strictly without Tamil accent): ',
  },
  {
    id: 'sinhala-news',
    label: 'Sinhala News (ප්‍රවෘත්ති)',
    description: 'Professional Sri Lankan news broadcast in pure Sinhala',
    examplePrefix: 'Speak in a clear, authoritative, native Sri Lankan Sinhala (සිංහල) news broadcast style with accurate Sinhalese pronunciation without any foreign/Tamil accent: ',
  },
  {
    id: 'whisper',
    label: 'Gentle Whisper',
    description: 'Soft, intimate, and calming tone',
    examplePrefix: 'In a gentle, comforting whisper: ',
  },
  {
    id: 'dramatic',
    label: 'Cinematic Drama',
    description: 'Deep, suspenseful, and intense delivery',
    examplePrefix: 'In a dramatic, suspenseful cinematic voice: ',
  },
  {
    id: 'professional',
    label: 'News & Tech Narration',
    description: 'Clear, authoritative, and structured cadence',
    examplePrefix: 'Speak in a clear, authoritative, professional news broadcast style: ',
  },
  {
    id: 'storyteller',
    label: 'Fantasy Storyteller',
    description: 'Expressive, magical, and captivating pacing',
    examplePrefix: 'Speak like an engaging fantasy storyteller narrating an epic tale: ',
  },
];

export const DEFAULT_DIALOGUE_TURNS: DialogueTurn[] = [
  {
    id: 'turn-1',
    speaker: 'Speaker1',
    voiceName: 'Puck',
    text: 'Welcome to our tech podcast! Today we are exploring how AI generates expressive voices.',
  },
  {
    id: 'turn-2',
    speaker: 'Speaker2',
    voiceName: 'Aoede',
    text: 'Speak in authentic native Sri Lankan Sinhala (ශ්‍රී ලාංකික සිංහල) without Tamil accent: ඔව්, ඒක ඇත්තටම පුදුම සහගතයි! අපට දැන් ඉංග්‍රීසි වගේම සිංහල භාෂාවෙනුත් ඉතා ස්වාභාවික සහ නිවැරදි හඬවල් නිර්මාණය කළ හැකියි.',
  },
  {
    id: 'turn-3',
    speaker: 'Speaker1',
    voiceName: 'Puck',
    text: 'With genuine excitement: Exactly! You can effortlessly mix languages and create bilingual audio dramas.',
  },
];

export const SAMPLE_TEXTS = [
  'Say cheerfully with a warm smile: Welcome to AI VOICE STUDIO BY V! We turn your words into lifelike speech with expressive emotional nuances.',
  'Speak in authentic native Sri Lankan Sinhala (ශ්‍රී ලාංකික සිංහල) with warm articulation without Tamil accent: ආයුබෝවන්! AI VOICE STUDIO BY V වෙත ඔබව සාදරයෙන් පිළිගනිමු. අපගේ නවීන කෘත්‍රිම බුද්ධි තාක්ෂණය හරහා ඉතා පැහැදිලි සිංහල හඬවල් නිර්මාණය කළ හැක.',
  'Speak in a clear, authoritative, native Sri Lankan Sinhala (සිංහල) broadcast style without any foreign accent: අද දින විශේෂ ප්‍රවෘත්ති: නවතම AI තාක්ෂණය මඟින් ලොව පුරා භාෂා රැසකින් ස්වාභාවික හඬවල් නිර්මාණය කිරීමේ හැකියාව දැන් තවත් පුළුල් කර ඇත.',
  'In a deep, cinematic, suspenseful tone: As the sun set below the horizon, an ancient secret awakened from the depths of the obsidian fortress.',
  'In a soft, soothing, relaxing whisper: Close your eyes, breathe in slowly... and let the gentle rhythm of peace wash over you.',
  'Speak with energetic professional enthusiasm: Introducing our revolutionary new platform, designed to empower creators everywhere with instant audio generation!',
];
